# Generated by Django 4.1.7 on 2023-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
    ]
