# Generated by Django 4.1.7 on 2023-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentimental_status',
            field=models.IntegerField(help_text='1-Positive, 0-Negative'),
        ),
    ]
