# Generated by Django 4.1.7 on 2023-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_sentimental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentimental_status',
            field=models.IntegerField("1:Positive, 0:Neutral , -1:Negative"),
        ),
    ]
