# Generated by Django 4.1.7 on 2023-03-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_category_alter_feedback_sentimental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(verbose_name='1:Teaching, 2: Course Content, 3:Examination, 4:Labwork, 5:Library Facilities, 6: Extracurriular Activities'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentimental_status',
            field=models.IntegerField(),
        ),
    ]
