# Generated by Django 4.1.7 on 2023-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(help_text='1:Teaching, 2: Course Content, 3:Examination, 4:Labwork, 5:Library Facilities, 6: Extracurriular Activities', max_length=20),
        ),
    ]
