# Generated by Django 4.1.7 on 2023-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.IntegerField(),
        ),
    ]
