# Generated by Django 4.1.7 on 2023-03-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
